 const products = [
    {
      id: "1",
      name: "Product 1",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 1.",
      category: "maquinas",
    },
    {
      id: "2",
      name: "Product 2",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 2.",
      category: "maquinas",
    },
    {
      id: "3",
      name: "Product 3",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 3.",
      category: "maquinas",
    },
    {
      id: "4",
      name: "Product 4",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 4.",
      category: "maquinas",
    },
    {
      id: "5",
      name: "Product 5",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 5.",
      category: "maquinas",
    },
    {
      id: "6",
      name: "Product 6",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 6.",
      category: "maquinas",
    },
    {
      id: "7",
      name: "Product 7",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 7.",
      category: "ferragens",
    },
    {
      id: "8",
      name: "Product 8",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 8.",
      category: "maquinas",
    },
    {
      id: "9",
      name: "Product 9",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 9.",
      category: "maquinas",
    },
    {
      id: "10",
      name: "Product 10",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 10.",
      category: "maquinas",
    },
    {
      id: "11",
      name: "Product 11",
      image: "/imgs/mock-products1.jpg", 
      description: "This is the description for Product 11.",
      category: "maquinas",
    },
];

export {products};